### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by upcFrost** [psi-4ward/docker-etcd-registrator#4]
Hi, i'm getting some troubles with registering an HTTPS backend with the registrator. Vulcand expects the type of the backend to be strictly "http" for both HTTP and HTTPS, and the registrator constructs the service URL using this type, while for HTTPS it should be "http" type and "https" in the URL.
I've made a small patch to fix it, it adds one more possible parameter for backend, URLType, which defaults to "http".
The part about the JSON.stringify() may seem a bit hardcoded, but i was not sure about any better 
way, and the filter like ['Type','Settings'] doesn't work well with nested dicts.
[docker_registrator_patch_http.txt](https://github.com/psi-4ward/docker-etcd-registrator/files/174359/docker_registrator_patch_http.txt)

**Comment by psi-4ward** [comment]
Please Test !
