### ISSUE TITLE
Proposal: Option to force the use of public IP

### ISSUE THREAD

**Issue by upcFrost** [psi-4ward/docker-etcd-registrator#6]
Hi,
This is just a proposal, sometimes it's useful to force the public IP registration, for example if the service is listening to the localhost and there is a proxy listening to the public ip on the same port.

Patch included, it adds one more env variable to be checked when setting the `service.ip` in the `container.js` and adds the description of this variable to the readme file.
[docker_registrator_patch_force_public_ip.txt](https://github.com/psi-4ward/docker-etcd-registrator/files/208414/docker_registrator_patch_force_public_ip.txt)

**Comment by psi-4ward** [comment]
I've added you as collaborator.
Feel free to apply the patch yourself.

**Comment by upcFrost** [comment]
Thanks :)
